# Generated by Django 4.2.7 on 2024-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidrequest',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب/عزباء'), ('married', 'متزوج/ة'), ('divorced', 'مطلق/ة'), ('widowed', 'أرمل/ة')], default='single', max_length=20, verbose_name='الحالة الاجتماعية'),
        ),
    ]
