# Generated by Django 4.2.7 on 2024-12-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_alter_aidrequest_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخبر')),
                ('content', models.TextField(verbose_name='محتوى الخبر')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='صورة الخبر')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charities.charity', verbose_name='الجمعية')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'أخبار',
                'ordering': ['-publication_date'],
            },
        ),
    ]
