# Generated by Django 4.2.7 on 2024-12-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_charitynews'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitynews',
            name='important_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مهم حتى تاريخ'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='خبر مهم'),
        ),
    ]
