# Generated by Django 4.2.7 on 2024-12-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0005_charitynews_is_breaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitynews',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر مشاهدة'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='tags',
            field=models.CharField(blank=True, help_text='أدخل الوسوم مفصولة بفواصل', max_length=500, verbose_name='الوسوم'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
    ]
