# Generated by Django 4.2.7 on 2024-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0006_charitynews_last_viewed_charitynews_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='assistance_link',
            field=models.URLField(blank=True, help_text='رابط خاص لتقديم المساعدات للمحتاجين من خلال هذه الجمعية', null=True, verbose_name='رابط تقديم المساعدات'),
        ),
    ]
