# Generated by Django 4.2.7 on 2024-12-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0007_charity_assistance_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='assistance_link',
        ),
        migrations.CreateModel(
            name='CharityAssistanceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الرابط')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الرابط')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_links', to='charities.charity', verbose_name='الجمعية')),
            ],
            options={
                'verbose_name': 'رابط مساعدة',
                'verbose_name_plural': 'روابط المساعدة',
                'ordering': ['created_at'],
            },
        ),
    ]
