# Generated by Django 4.2.7 on 2024-12-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0008_remove_charity_assistance_link_charityassistancelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='facebook_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على فيسبوك'),
        ),
        migrations.AddField(
            model_name='charity',
            name='instagram_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على انستقرام'),
        ),
        migrations.AddField(
            model_name='charity',
            name='last_social_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر نشر اجتماعي'),
        ),
        migrations.AddField(
            model_name='charity',
            name='social_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='وصف للنشر الاجتماعي'),
        ),
        migrations.AddField(
            model_name='charity',
            name='social_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='صورة للنشر الاجتماعي'),
        ),
        migrations.AddField(
            model_name='charity',
            name='social_publish',
            field=models.BooleanField(default=False, verbose_name='نشر على وسائل التواصل'),
        ),
        migrations.AddField(
            model_name='charity',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على تلقرام'),
        ),
        migrations.AddField(
            model_name='charity',
            name='twitter_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على تويتر'),
        ),
        migrations.AddField(
            model_name='charity',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على واتساب'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='facebook_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على فيسبوك'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='instagram_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على انستقرام'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='last_social_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر نشر اجتماعي'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='social_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='وصف للنشر الاجتماعي'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='social_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='صورة للنشر الاجتماعي'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='social_publish',
            field=models.BooleanField(default=False, verbose_name='نشر على وسائل التواصل'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على تلقرام'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='twitter_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على تويتر'),
        ),
        migrations.AddField(
            model_name='charityassistancelink',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على واتساب'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='facebook_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على فيسبوك'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='instagram_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على انستقرام'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='last_social_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر نشر اجتماعي'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='social_description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='وصف للنشر الاجتماعي'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='social_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/', verbose_name='صورة للنشر الاجتماعي'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='social_publish',
            field=models.BooleanField(default=False, verbose_name='نشر على وسائل التواصل'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على تلقرام'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='twitter_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على تويتر'),
        ),
        migrations.AddField(
            model_name='charitynews',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False, verbose_name='نشر على واتساب'),
        ),
    ]
