# Generated by Django 4.2.7 on 2024-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0009_charity_facebook_enabled_charity_instagram_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitynews',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='النشر على تلجرام'),
        ),
    ]
