# Generated by Django 4.2.7 on 2024-12-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0010_alter_charitynews_telegram_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charitynews',
            name='instagram_enabled',
            field=models.BooleanField(default=False, verbose_name='النشر على انستقرام'),
        ),
    ]
